### ISSUE TITLE
登录流程

### ISSUE THREAD

**Issue by flyer1111** [MiEcosystem/mijia_ble_secure#1]
app发送开门指令的时候,蓝牙协议栈抛上来了两个事件0x50和0x51,为什么会上抛两个事件?
蓝牙侧,如何和米家app交互 的

**Comment by 0xabadc0fe** [comment]
1. 0x50,0x51 分别是 nordic 蓝牙栈的事件，详情参见 nordic SDK document
2. 米家仅建立安全通道，交互是通过开发者自定义 service 实现的
