### ISSUE TITLE
门锁调试apk连接高安全门锁时连接失败，安全认证失败，错误代码-28

### ISSUE THREAD

**Issue by xiaoyongge** [MiEcosystem/mijia_ble_secure#11]
目前使用 门锁调试apk连接高安全门锁时连接失败，安全认证失败，错误代码-28。帮忙分析原因
apk上显示：
![image](https://user-images.githubusercontent.com/12733226/58533419-0d471180-821b-11e9-8280-1ba0a64d2ffd.png)
 设备日志：
![image](https://user-images.githubusercontent.com/12733226/58533427-146e1f80-821b-11e9-83e9-8dc79b3f1905.png)

**问题描述**
问题具体现象
设备端详细 log 信息（只保留 mijia ble libs log 即可, 删除自己开发过程添加的 log ）

**如何复现**
如何使用原生工程进行复现，以及详细操作步骤。

**期望结果**
描述一下 bug 修复后的结果

**环境描述**
SoC 硬件平台
SoC SDK 版本
mijia ble libs 版本：可具体到 commit
手机机型
操作系统版本
App 版本

**其他补充**

**Comment by xiaoyongge** [comment]
1、触发 button0，发送EXT_SIGNAL_PB0_SHORT_PRESS 信号。
2、执行 advertising_init(1);
然后APP就显示认证失败（-28）

没有更多log了。

**Comment by xiaoyongge** [comment]
修改了IIC引脚定义，修改了pid，增加了虚拟按键触发联网

**Comment by 0xabadc0fe** [comment]
从 log 看设备端没有收到开始绑定的请求，更新完连接参数后直接断开了。断开原因2 是 `REMOTE_USER_TERMINATED` 即手机端发起断开。

**Comment by dingshaoran** [comment]
帮忙给一份 android 的 logcat 所有 log。我看一下啊是哪个步骤报错了。

**Comment by xiaoyongge** [comment]
关闭了低功耗电源管理来调试，导致出现以上问题，重新打开电源管理函数，目前问题已解决，关闭问题。
