### ISSUE TITLE
设备恢复出厂设置，APP提示未找到门锁

### ISSUE THREAD

**Issue by flyer1111** [MiEcosystem/mijia_ble_secure#13]
**问题描述**
问题具体现象 设备恢复出厂设置，APP不删除门锁，登录提示未找到门锁，不提示已经恢复出厂设置
设备端详细 log 信息（只保留 mijia ble libs log 即可, 删除自己开发过程添加的 log ）
[0m<info> app: Connected.[0m
[1;33m[W] mi srv: Connected Peer MAC:
[0m 78 B5 AA 07 38 74      |x氮.8t
[0m[I] mi srv: default interval min: 48 ms, max: 48 ms
[0m[0m<info> app:  opcode_parse auth_value=0x00000020
[0m
[1;33m[W] secure auth:  START 0x00000020

[0m[0m<info> app: schd_tick_timer stop[0m
[0m<info> app: schd_tick_timer start
[0m
[0m[I] : USER CUSTOM CALLBACK RECV EVT ID 4
[0m[1;33m[W] secure auth: monitor power off
[0m[0m<info> app: Disconnected.[0m
[0m<info> app: BLE_GAP_EVT_DISCONNECTED = 0x13
 
返回给APP也是正确的
static void admin_login_procedure()
{
    if (m_is_registered != true) {
        opcode_send(ERR_NOT_REGISTERED);
        enqueue(&monitor_queue, (uint8_t []) {SCHD_EVT_ADMIN_LOGIN_FAILED});
        return;
    }
**如何复现**
如何使用原生工程进行复现，以及详细操作步骤。

**期望结果**
设备已经恢复出厂设置，APP登录时提示已经恢复出厂设置

**环境描述**
SoC 硬件平台 nrf52832
SoC SDK 版本 SDK15.20
mijia ble libs 版本：dc6c83f4f194eb1cba941c7b3d91322adc0c0a8e
手机机型 华为MLA
操作系统版本 android
App 版本
5.5.10和5.5.15
**其他补充**

**Comment by 0xabadc0fe** [comment]
请移步 App 开发者仓库提 issue 修改提示内容
