### ISSUE TITLE
GATT协议里的lock service的UUID固定吗？characteristic能增加自定义项吗？

### ISSUE THREAD

**Issue by xiaoyongge** [MiEcosystem/mijia_ble_secure#15]
问一下GATT协议里面lock service的UUID是固定不能改的吗？service下面的character能否增加自定义项？还是只能在lock.operator里面传输自定义数据？

**Comment by 0xabadc0fe** [comment]
lock service UUID 不能修改，也不能增加 char；
如需传输其他自定义数据，请新建自定义服务；
