### ISSUE TITLE
检测不到蓝牙设备

### ISSUE THREAD

**Issue by bwc2019** [MiEcosystem/mijia_ble_secure#16]
用keil成功编译和下载，但手机端检测不到该蓝牙设备

**Comment by bwc2019** [comment]
按照米家高安全BLE接入产品开发文档，前六步已成功执行；
执行第七步时，打开米家APP，开启蓝牙，发现附近的设备，一直搜索不到，请帮忙分析一下原因！！！

**Comment by 0xabadc0fe** [comment]
请按照 issue 模版反馈问题

**Comment by 0xabadc0fe** [comment]
请直接参考 issue #18
