### ISSUE TITLE
无法检测到设备

### ISSUE THREAD

**Issue by bwc2019** [MiEcosystem/mijia_ble_secure#18]
**问题描述**
按照米家高安全BLE接入产品开发文档，前六步已成功执行；
执行第七步时，打开米家APP，开启蓝牙，发现附近的设备，一直搜索不到，请帮忙分析一下原因！！！

**如何复现**
1.打开宏
#ifndef MI_BLE_ENABLED
#define MI_BLE_ENABLED
#endif

#ifndef MI_LOG_ENABLED
#define MI_LOG_ENABLED
#endif

#ifndef MI_ASSERT
#define MI_ASSERT
#endif

#ifndef HAVE_MSC
#define HAVE_MSC               2
#endif
2.修改配置
#if defined(BOARD_PCA10028)
#define MSC_PWR_PIN 12
const iic_config_t iic_config = {
        .scl_pin  = 1,
        .sda_pin  = 2,
        .freq = IIC_100K
};
#elif defined(BOARD_PCA10040)
#define MSC_PWR_PIN 23
const iic_config_t iic_config = {
        .scl_pin  = 24,
        .sda_pin  = 25,
        .freq = IIC_100K
};
#endif
3.在main函数中添加log
NRF_LOG_INIT(NULL);

    // Initialize stack and SDK modules.
    timers_init();
 
  MI_LOG_INFO("main......1\n");
    buttons_leds_init();
   MI_LOG_INFO("main......2\n");
    ble_stack_init();
   MI_LOG_INFO("main......3\n");
    gap_params_init();
   MI_LOG_INFO("main......4\n");
    services_init();
   MI_LOG_INFO("main......5\n");
    advertising_init(false);
   MI_LOG_INFO("main......6\n");
    conn_params_init();
   MI_LOG_INFO("main......7\n");

    time_init(NULL);
4.编译后下载成功
![image](https://user-images.githubusercontent.com/52914317/61684746-01745900-ad4d-11e9-876e-03b2a3f4a6c5.png)
![image](https://user-images.githubusercontent.com/52914317/61684770-12bd6580-ad4d-11e9-821c-88380f3d5180.png)
5.没有log信息输出且搜索不到蓝牙设备
**期望结果**
希望可以输出log并想知道搜索不到设备的问题出在哪里
**环境描述**

**其他补充**
同样的操作，运行另外的app可以成功输出log且能搜索到设备

**Comment by 0xabadc0fe** [comment]
1. 有没有烧写 nordic softdevice S130 ？如果没有，请参考一下 nordic 开发文档，如果还不知道怎么做请咨询原厂FAE。
2. `MI_LOG_ENABLED` 应该添加到工程配置中，这样所有的文件都会打印 log。

**Comment by bwc2019** [comment]
现在通过手机蓝牙已经可以搜索到设备，但是通过米家APP搜多附近设备时搜索不到，是“小米蓝牙安全开发板”白名单没有开通的原因吗？

**Comment by 0xabadc0fe** [comment]
对，请发邮件申请开通白名单权限，邮件中提供米家账号

**Comment by bwc2019** [comment]
我们用的不是”小米蓝牙安全开发板”，我们有自己的pid，我们用NRF connect数据是通的，但是进入米家app搜索不到我们设备，需要怎么配置？

**Comment by 0xabadc0fe** [comment]
[参考开发者平台文档](https://iot.mi.com/new/guide.html?file=03-平台使用指南/01-账号权限管理/03-权限管理) 给你们的测试账户添加白名单权限

**Comment by bwc2019** [comment]
![image](https://user-images.githubusercontent.com/52914317/61936331-13f5c900-afbf-11e9-9430-9c48c6e51986.png)
![image](https://user-images.githubusercontent.com/52914317/61936365-27089900-afbf-11e9-987c-55c629f8bbcb.png)

是这个地方吗？我们的账户都在这里面；

下面这张图片是我们手机能搜索到的其他设备：

![image](https://user-images.githubusercontent.com/52914317/61936492-7222ac00-afbf-11e9-8d03-677f871f6c6d.png)

**Comment by bwc2019** [comment]
![image](https://user-images.githubusercontent.com/52914317/61943459-085dce80-afce-11e9-8e77-7e69981cbd28.png)
请问一下图中红框中的error是什么原因导致的，对连接是否有影响？

**Comment by 0xabadc0fe** [comment]
没有影响

**Comment by bwc2019** [comment]
我们已经按照开 发者平台文档 添加白名单，但是米家app还是搜索不到，请帮忙分析一下可能是什么原因导致的？

**Comment by 0xabadc0fe** [comment]
App 的问题请移步 App SDK 仓库反馈。

**Comment by bwc2019** [comment]
我是从手机应用商店里面下载的米家APP，或者是开发板的米家APP也都搜索不到，请问是什么原因导致的？

**Comment by 0xabadc0fe** [comment]
请咨询对接的产品经理 或者 App 插件开发
