### ISSUE TITLE
新产品注册绑定时提示安全验证失败-28

### ISSUE THREAD

**Issue by xiaoleixd** [MiEcosystem/mijia_ble_secure#23]
智能门锁与米家APP联调注册绑定功能。锁端蓝牙广播版本号是v5，APP可以与锁建立连接，锁收到APP发送的AUTH = REG_START和Secure AUTH = partical(app_pub)消息，但是过几秒后APP显示安全认证失败（错误码-28）。
请问是什么原因导致此错误发生？锁收到APP发送的Secure AUTH = partical(app_pub)消息后，需要给APP返回应答消息吗？看序列图说明APP发送完Secure AUTH消息后就显示paircode。
![图1](https://user-images.githubusercontent.com/49562212/62777768-08d38a80-bae1-11e9-9b44-f83d6b4ead24.png)
![截屏_20190807_004010](https://user-images.githubusercontent.com/49562212/62777808-27d21c80-bae1-11e9-9bb3-de3e613ebbb7.jpg)

**Comment by 0xabadc0fe** [comment]
请按照模版提问，并粘贴设备侧 log
