### ISSUE TITLE
蓝牙锁安全验证

### ISSUE THREAD

**Issue by bwc2019** [MiEcosystem/mijia_ble_secure#24]
**问题描述**
![image](https://user-images.githubusercontent.com/52914317/63142775-c39de400-c01d-11e9-8711-d6636cdd4e13.png)
我们的蓝牙设备只有按键，没有屏，请问是否有别的方式来验证？该如何做？

我们尝试着改变输入方式，没有效果。

mibeacon_capability_t cap = {.connectable = 1,
                                 .encryptable = 1,
                                 .bondAbility = 1,
                 .IO_capability = 0
                                };
    //mibeacon_cap_sub_io_t IO = {.in_digits = 1};
  mibeacon_cap_sub_io_t IO = {0};
    mible_addr_t dev_mac;
    mible_gap_address_get(dev_mac);

    mibeacon_config_t mibeacon_cfg =
    {
        .frame_ctrl = frame_ctrl,
        .pid = PRODUCT_ID,
        .p_mac = (mible_addr_t *)dev_mac,
        .p_capability = &cap,
        .p_cap_sub_IO = &IO,
        .p_obj = NULL,
    };

**如何复现**
在米家app中进行蓝牙设备绑定。

**期望结果**

**环境描述**
蓝牙芯片：nrf51802
加密芯片：mja1

**其他补充**

**Comment by bwc2019** [comment]
我们只有几个功能键

**Comment by 0xabadc0fe** [comment]
没有 IO 能力的设备，请选择使用 二维码绑定。
具体细节请咨询产品经理。
