### ISSUE TITLE
蓝牙锁一次性密码获取

### ISSUE THREAD

**Issue by dlutfrank** [MiEcosystem/mijia_ble_secure#25]
**问题描述**
获取一次性密码组无法和APP端匹配
![image](https://user-images.githubusercontent.com/8346691/63315354-77b0af00-c33d-11e9-922c-1d61afdc6ca6.png)

**尝试过的操作**

通过APP获取10分钟间隔的密码组，一共有8个，记录下获取密码的时间戳。

将该时间戳传入到固件中，调用固件中获取一次性密码的函数。

固件端得到32个字节的字节流，将32个字节拆分成8组，每组4个字节。将每组的4个字节转换为数字，无法和APP端的密码对应上。

**如何复现**
如何使用原生工程进行复现，以及详细操作步骤。

**期望结果**
能有描述固件端生成一次性密码的API说明

**环境描述**
SoC 硬件平台
SoC SDK 版本
mijia ble libs 版本：可具体到 commit
手机机型
操作系统版本
App 版本

**其他补充**

**Comment by dlutfrank** [comment]
SoC 硬件平台        NRF52832
SoC SDK 版本      15.2.0
mijia ble libs 版本：  2.1.11
手机机型         iphone 5s
操作系统版本   IOS11.4.1
App 版本         米家： V4.20.4

**Comment by 0xabadc0fe** [comment]
1. 请确保设备和App 的时间同步
2. log 现实的参数 refresh time interval 数值范围明显不对。请参看`mible_secure_auth.h`中详细接口定义。
