### ISSUE TITLE
OTA疑问

### ISSUE THREAD

**Issue by bwc2019** [MiEcosystem/mijia_ble_secure#26]
**问题描述**
我们使用的蓝牙芯片：nrf51802（带有加密芯片），现在想对蓝牙进行OTA升级，查看了系统代码，

#if defined (MI_BLE_ENABLED)
#include "secure_auth/mible_secure_auth.h"
#define SUPPORT_GATT_DFU 0
#elif defined(MI_MESH_ENABLED)
#include "mesh_auth/mible_mesh_auth.h"
#define SUPPORT_GATT_DFU 1
#endif

现在有如下疑问：  
1）系统只有MI_MESH_ENABLED=true情况下才具备OTA功能；
还是在MI_BLE_ENABLED = true 情况下将SUPPORT_GATT_DFU 置为 1 的时，也可以进行OTA？
2）蓝牙固件OTA升级需要我们自己去实现吗？

**如何复现**

**期望结果**

**环境描述**
蓝牙芯片：nrf51802
加密芯片：mja1

**其他补充**

**Comment by 0xabadc0fe** [comment]
1. 不可以
2. 需要你们自己实现 OTA

**Comment by bwc2019** [comment]
RN里面有没有类似于android 里面 no.nordicsemi.android:dfu 这种实现DFU的库，如果没有这种库，请问有什么好的方法可以参考吗？
