### ISSUE TITLE
android 连接时报 disconnect 13

### ISSUE THREAD

**Issue by flyer1111** [MiEcosystem/mijia_ble_secure#3]
1.帮忙分析什么情况disconnect 13 蓝牙连接问题，需要退出插件再进入连接OK
日志如下：
 0> BEACON:INFO:mibeacon_data_set is_encrypt NO
 0> BEACON:INFO:mibeacon event adv ...
 0> BEACON:INFO:mibeacon event adv end.
 0> Connected Peer MAC: 5E 69 94 58 5A 65                                ^i?XZe          
 0> Conn param default: min 39, max 39
 0> SCHD:WARNING: START 20
 0> 
 0> USER CUSTOM CALLBACK RECV EVT ID 8
 0> SCHD:ERROR:msc_power_off
 0> Disconnect reason 13.
 0> LOCK:ERROR:disconnected!!!
 0> Connected Peer MAC: 5E 69 94 58 5A 65                                ^i?XZe          
 0> Conn param default: min 39, max 39
 0> SCHD:ERROR:msc_power_off
 0> Disconnect reason 13.
 0> LOCK:ERROR:disconnected!!!

**Comment by 0xabadc0fe** [comment]
1. 软件版本是多少？ GitHub上哪一次提交？
2. EVT ID 8:  SCHD_EVT_KEY_NOT_FOUND 表明当前门锁还未绑定，所以无法进行登陆。

**Comment by flyer1111** [comment]
SDK版本是12.3，使用4月23更新的GitHub commit 37112de5e3f79c4f8db57e66e3d81a25ac45755b

**Comment by flyer1111** [comment]
Connected Peer MAC: 55 8D EC 5B 52 6B                                U??[Rk          
 0> Conn param default: min 39, max 39
 0> Conn param update : min 6, max 6
 0> SCHD:WARNING: START 20
 0> 
 0> SCHD:ERROR:msc_power_on
 0> Conn param update : min 39, max 39
 0> SCHD:ERROR:msc_power_off
 0> Disconnect reason 13.
 0> LOCK:ERROR:disconnected!!!

**Comment by flyer1111** [comment]
你好，这个是第一次绑定登陆成功之后，断开蓝牙，在重新连接登录，再也登录不成功了
 send app done!!!!!!!!! 
 0> MAIN:WARNING:MCU rts done
 0> MAIN:ERROR:uart close !
 0> SCHD:ERROR:msc_power_off
 0> Disconnect reason 13.
 0> LOCK:ERROR:disconnected!!!
 0> Connected Peer MAC: 55 8D EC 5B 52 6B                                U??[Rk          
 0> Conn param default: min 39, max 39
 0> Conn param update : min 6, max 6
 0> SCHD:WARNING: START 20
 0> 
 0> SCHD:ERROR:msc_power_on
 0> Conn param update : min 39, max 39
 0> SCHD:ERROR:msc_power_off
 0> Disconnect reason 13.
 0> LOCK:ERROR:disconnected!!!
 0> Connected Peer MAC: 55 8D EC 5B 52 6B                                U??[Rk          
 0> Conn param default: min 39, max 39
 0> SCHD:INFO:Start MSC cmd 0x3B @ schd_time 2
 0> BLEM:INFO:ACK 00 00 01 04                                      ....            
 0> USER CUSTOM CALLBACK RECV EVT ID 7
 0> SCHD:ERROR:msc_power_off
 0> Disconnect reason 13.
 0> LOCK:ERROR:disconnected!!!
 0> Connected Peer MAC: 55 8D EC 5B 52 6B                                U??[Rk          
 0> Conn param default: min 39, max 39
 0> SCHD:WARNING: START 20
 0> 
 0> SCHD:ERROR:msc_power_on
 0> SCHD:ERROR:msc_power_off
 0> Disconnect reason 13.
 0> LOCK:ERROR:disconnected!!!
 0> SCHD:INFO:Start MSC cmd 0x3B @ schd_time 2
 0> USER CUSTOM CALLBACK RECV EVT ID 7
 0> Connected Peer MAC: 55 8D EC 5B 52 6B                                U??[Rk          
 0> Conn param default: min 39, max 39
 0> SCHD:WARNING: START 20
 0> 
 0> SCHD:ERROR:msc_power_on
 0> SCHD:INFO:Start MSC cmd 0x3B @ schd_time 2
 0> MAIN:ERROR:TWI evt error 2.
 0> BLEM:INFO:ACK 00 00 01 01                                      ....            
 0> BLEM:INFO:ACK 00 00 01 00                                      ....            
 0> USER CUSTOM CALLBACK RECV EVT ID 7
 0> Conn param update : min 159, max 159
 0> SCHD:ERROR:msc_power_off
 0> Disconnect reason 13.
 0> LOCK:ERROR:disconnected!!!

**Comment by 0xabadc0fe** [comment]
从 log 看 Start MSC cmd 0x3B 后就没有收到响应，证明安全芯片进入异常状态，请检查安全芯片电源控制引脚。

**Comment by flyer1111** [comment]
第一次断开连接时在这里
 Connected Peer MAC: 55 8D EC 5B 52 6B U??[Rk
0> Conn param default: min 39, max 39
0> Conn param update : min 6, max 6
0> SCHD:WARNING: START 20
0>
0> SCHD:ERROR:msc_power_on
0> Conn param update : min 39, max 39
0> SCHD:ERROR:msc_power_off
0> Disconnect reason 13.
0> LOCK:ERROR:disconnected!!!

**Comment by 0xabadc0fe** [comment]
抱歉，你所提供的 log 看不出任何问题。

**Comment by flyer1111** [comment]
需要抓那些log

**Comment by 0xabadc0fe** [comment]
> 从 log 看 Start MSC cmd 0x3B 后就没有收到响应，证明安全芯片进入异常状态，请检查安全芯片电源控制引脚。

可以尝试用 GitHub 工程试复现一下，若不可复现则证明这个问题是后期开发引入的，需要你们自己debug。
