### ISSUE TITLE
clone master和nordic分支后mijia_ble_api和mijia_ble_libs都为空

### ISSUE THREAD

**Issue by andrepan** [MiEcosystem/mijia_ble_secure#4]
clone master和nordic分支后mijia_ble_api和mijia_ble_libs都为空，git提示如下：

“Failed to clone 'mijia_ble_libs' a second time, aborting”

clone命令用的是"git clone --recursive https://github.com/MiEcosystem/mijia_ble_secure.git"

**Comment by 0xabadc0fe** [comment]
mijia_ble_libs 是私有仓库，需要向负责项目的PM申请访问权限。
mijia_ble_api 是公开的仓库，请检查网络环境。
