### ISSUE TITLE
连接过程中提示NON-START OPCODE

### ISSUE THREAD

**Issue by flyer1111** [MiEcosystem/mijia_ble_secure#5]
0> BEACON:INFO:mibeacon_data_set is_encrypt NO
 0> BEACON:INFO:mibeacon event adv ...
 0> Conn param update : min 6, max 6
 0> BLEM:WARNING:NON-START OPCODE DE85CA90
 0> Disconnect reason 13.
 0> LOCK:ERROR:disconnected!!!

**Comment by 0xabadc0fe** [comment]
App 发送了错误的 opcode, 可能是因为设备发送的 mibeacon 格式不对，导致 App 认为设备是一个普通 BLE 设备。

**Comment by flyer1111** [comment]
是我更新了mibeacon最新格式，是不是需要跟新App

**Comment by 0xabadc0fe** [comment]
请仔细检查你修改的内容。（也可以看看 demo 工程是如何配置的）
另外，这里的 issue 本应针对 mijia ble secure 软件设计上存在的缺陷提出，而不是指导每一步开发过程。
遇到问题可以先用 demo 工程试复现一下，若不可复现则多半说明是后期开发引入，需要你们自己debug。

**Comment by flyer1111** [comment]
我用demo也是一样的效果，也是报这个错误。

**Comment by 0xabadc0fe** [comment]
> 我用demo也是一样的效果，也是报这个错误。

抱歉，我测试了 nordic & nordic legacy 的代码无法复现你的现象。

**Comment by flyer1111** [comment]
我用的11月5日的sdk，有这个问题，我看了最新的sdk都是基于SDK 15.20 的，我用的之前的SDK 12.30，我看最新的代码加了随机数的，有没有SDK 12.30 的patch

**Comment by 0xabadc0fe** [comment]
请注明所使用分支以及commit

**Comment by flyer1111** [comment]
分支 master
0d84824596e918dc49b6232b07926c700af0e34c

commit 0d84824596e918dc49b6232b07926c700af0e34c (HEAD -> master, origin/nordic_legacy, origin/master, origin/HEAD)
Author: Tian <jiangtian@xiaomi.com>
Date:   Sun Nov 4 03:29:32 2018 +0800

    temporary cancel the session expire mechanism

**Comment by flyer1111** [comment]
你好，我们在调试的时候遇到  secure auth: Confirmation failed.
加log看是random.dev和random.app 值不同

![image](https://user-images.githubusercontent.com/42274809/49265156-fef68380-f48b-11e8-9082-4b8cf1dcf3eb.png)

**Comment by 0xabadc0fe** [comment]
1. 之前发送 OPCODE DE85CA90 的问题已经解决了吗？解决方法的能不能分享一下？
2. 键盘输入字符应按照 ASCII 解析，例如 'A' = 0x41, '0' = 0x30

**Comment by flyer1111** [comment]
解决了，时加密芯片的管脚配置错误导致的，damo和我们的单本使用管脚不同。
谢谢啊

**Comment by flyer1111** [comment]
姜工，你好，现在是否还需要我们自己定义服务和特征值（非蓝牙开门），ios和android是否已经归一。
