### ISSUE TITLE
OTA固件升级

### ISSUE THREAD

**Issue by xfengltl** [MiEcosystem/mijia_ble_secure#6]
手机点击设备升级，设备会打样一句log信息：[I] mi srv: update interval max: 159, min: 159

官方提供的SDK的OTA功能有没有开通？ 还是需要设置一些参数？

**Comment by 0xabadc0fe** [comment]
`[I] mi srv: update interval max: 159, min: 159`
Log 为连接参数更新事件，和 OTA 功能无关。
米家固件 middleware 暂不对 BLE 设备开放 OTA 功能。
