### ISSUE TITLE
事件消息接收异常

### ISSUE THREAD

**Issue by Banson-ZHANG** [MiEcosystem/mijia_ble_secure#8]
事件消息正常接收的情况下（较大量的数据，实时接收），app删掉锁，锁清空，重新注册后，收不到事件消息，已检查，消息已广播给网关，请帮忙定位问题，谢谢

**Comment by 0xabadc0fe** [comment]
抱歉，仅凭问题描述无法详细定位网关问题，请邮件联系产品对接负责人，申请查询网关日志。
