### ISSUE TITLE
IOS绑定失败无错误码

### ISSUE THREAD

**Issue by flyer1111** [MiEcosystem/mijia_ble_secure#9]
0> [I] secure auth: dev_confirmation sent @ schd_ticks 863
 0> [I] secure auth: app_confirmation received @ schd_ticks 869
 0> [I] secure auth: dev_random sent @ schd_ticks 881
 0> [I] secure auth: app_random received @ schd_ticks 887
 0> <info> app: Disconnected.
 0> <info> app: BLE_GAP_EVT_DISCONNECTED = 0x13

**Comment by 0xabadc0fe** [comment]
更新 mijia ble libs 到 secure-auth-2.1.11

**Comment by flyer1111** [comment]
我用最新的2.2.5 不行还是提示这个

**Comment by 0xabadc0fe** [comment]
你们之前在使用的 libs 是 2.2.x 还是 2.1.x ?
如果是 2.1.x 请使用 2.1.11 测试

**Comment by flyer1111** [comment]
2.2.4

**Comment by flyer1111** [comment]
这个分支nordic_secure_auth_2.2.0

**Comment by 0xabadc0fe** [comment]
你们的产品 model 是什么，Product ID 是多少？
目前仅米家智能门锁支持 2.2.x 协议。
非米家系列产品，请使用 2.1.11 协议。

**Comment by flyer1111** [comment]
好的谢谢
